### ISSUE TITLE
Command Line to launch coffee-cup with parameters (CMD)

### ISSUE THREAD

**Issue by AskDesignTeam** [demarque/coffee-cup#1]
Hello
I would like to opens a particular text file at a particular line. i test this but parameters doesn't work
'"E:\CoffeeCup Software\CoffeeCup Free HTML Editor\Coffee.exe"', '"C:\temp\test.txt" -g 80'

**Comment by jpbougie** [comment]
Hello! You should probably try to reach support for this commercial software: https://www.coffeecup.com/help/

This is an open source library for the CoffeeScript language, so sadly we cannot help you with operating that unrelated software.
